### PR TITLE
rename 'src' to 'bikedna'

### LINKED ISSUE #1: rename 'src' to 'bikedna'
xref https://github.com/anerv/BikeDNA_BIG/issues/1

### PR DESCRIPTION
**Pull request by anastassiavybornova**
resolves #1 

changes:

* replaced 'src' by 'bikedna' everywhere (folder name, in all .py and .ipynb files, in notebook readme)
* removed src.egg folder (but **not** adding bikedna.egg folder, i don't think we need it?) @anerv @jGaboardi
* tested/ran all notebooks before and after changes (with config and input files from `GeoDanmark` branch) - worked both times 
* tested installation by running `pip install git+https://github.com/anerv/BikeDNA.git@anvy-src-edit` in a test conda env, after this i was able to run & use `from bikedna import matching_functions`

questions @jGaboardi :

* we'll go with this repo, bikedna (instead of bikedna_big, since the latter was more of a helper repo for a single project)
* you mentioned "several small changes" necessary in `setup.py`, the only thing i changed is **~src~bikedna** though, can you check if anything else is necessary here?
* (once it's merged) unsure how to add bikedna to our simplification env file? or does it have to be pip installed manually after?

### CODE REVIEW

**Comment by anastassiavybornova** [comment]
ps: @anerv the environment.yaml file didn't work for me, i added the one i used (environment_minimal but without referring to miniconda), just for the records - but you can delete it again if you want

**Comment by jGaboardi** [comment]
> but not adding bikedna.egg folder, i don't think we need it?

Correct. Don't need.

> you mentioned "several small changes" necessary in setup.py, the only thing i changed is ~~src~~**bikedna** though, can you check if anything else is necessary here?

I try to carve out some time this weekend for this.

> (once it's merged) unsure how to add bikedna to our simplification env file? or does it have to be pip installed manually after?

I will provide an example.

> we'll go with this repo, bikedna (instead of bikedna_big, since the latter was more of a helper repo for a single project)

Just so I understand perfectly, the updates will be here in `bikedna`, not in `bikedna_big` (xref: https://github.com/anerv/BikeDNA_BIG/issues/1), correct?

**Comment by anastassiavybornova** [comment]
> Just so I understand perfectly, the updates will be here in `bikedna`, not in `bikedna_big` (xref: [anerv/BikeDNA_BIG#1](https://github.com/anerv/BikeDNA_BIG/issues/1)), correct?

exactly!

**Comment by jGaboardi** [comment]
@anastassiavybornova 

> you mentioned "several small changes" necessary in setup.py, the only thing i changed is ~~src~~**bikedna** though, can you check if anything else is necessary here?

I think you are correct with all the updates you made in this PR for minimal changes to get this package installable as `bikedna` (minimal is good). I tried to install locally with your changes and it appears to be successful. As time permits we can iterate over PRs to get the repo/package fully modernized (e.g. infrastructure, testing, CI, etc.) – assuming this is desired, of course.

> (once it's merged) unsure how to add bikedna to our simplification env file? or does it have to be pip installed manually after?

You can add this to any environment file by adding the snippet below; that can be in the environment in this repo or anywhere:

```
  - pip
  - pip:
    - git+https://github.com/anerv/BikeDNA.git@main
```

See an example of that in the wild over in `spopt`[^1]

[^1]: https://github.com/pysal/spopt/blob/fa782a5cb0ead740f3776c2f305522014515f5eb/environment.yml#L33-L34

**Comment by anastassiavybornova** [comment]
@jGaboardi 

> I think you are correct with all the updates you made in this PR for minimal changes to get this package installable as `bikedna` (minimal is good). I tried to install locally with your changes and it appears to be successful. As time permits we can iterate over PRs to get the repo/package fully modernized (e.g. infrastructure, testing, CI, etc.) – assuming this is desired, of course.

cool! then i think for now @anerv if you're fine with the changes, this PR could be merged; that way we already have what we need for the simplification project at this stage; and if we want to modernize this later we'll iterate some more

> You can add this to any environment file by adding the snippet below; that can be in the environment in this repo or anywhere

cool, good to know, thanks!!

**Comment by anerv** [comment]
Cool, I'll take care of the merge and create a new release.
@anastassiavybornova as we discussed earlier, the matching functions were not really designed to be generally applicable (there are a lot of baked in assumptions about the type of input data set, one-to-many matching of the OSM data etc). So if more work are to be put into this the functionality would require a general overhaul - which makes more sense to do outside of the bikedna context/repo

**Comment by anastassiavybornova** [comment]
@anerv thanks for this!! :) 

> the matching functions were not really designed to be generally applicable (there are a lot of baked in assumptions about the type of input data set, one-to-many matching of the OSM data etc). So if more work are to be put into this the functionality would require a general overhaul - which makes more sense to do outside of the bikedna context/repo

yes! aware of that. for now, we're using the feature matching for OSM data vs. reference data where OSM-one-to-many makes sense, so for our narrow use case it's fine as it is. agree that it's a good idea to later take things outside of the bikedna repo if this is to be used more generally.

**Pull request merged**
